name: build ci                    
on:                                  
  push:
    branches:
      - develop 
      
jobs:                                
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: package install
      run: yarn install
        
    - name: build
      run: yarn build

    - name: Lint
      run: yarn lint
